// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Create_Gift_Success")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Create_PropertiesAreNotNull_NotNull")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Properties_AssignNull_ThrowArgumentNullException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Create_PropertiesAreNotNull_NotNull(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Create_PropertiesAreNotNull_NotNull(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Create_PropertiesWhiteSpace_ThrowArgumentException(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Create_PropertiesAreNull_ThrowArgumentNullException(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Create_PropertiesAreNull_ThrowArgumentNullException(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Create_PropertiesWhiteSpace_ThrowArgumentException(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Create_TitleWhiteSpace_ThrowArgumentException(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1054:Uri parameters should not be strings", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.GiftTests.Create_TitleWhiteSpace_ThrowArgumentException(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.UserTests.Create_User_Success")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.UserTests.Create_PropertiesWhiteSpace_ThrowArgumentException(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Business.Tests.UserTests.Create_PropertiesAreNull_ThrowArgumentNullException(System.Int32,System.String,System.String)")]
